### ISSUE TITLE
Setting Up the Development Environment

### ISSUE THREAD

**Issue by stevecoding100** [stevecoding100/ZenkaiAnime-Ecommerce#2]
- Initialize a Git repository for version control.
- Npm init -y
- Set up the development environment for both front-end (React.js) and back-end (Node.js, Express.js).
- Install all necessary dependencies (pg, morgan, express, uuid, jsonwebtoken, nodemon, bcrypt, dotenv, ect)
- Create a server & client folder
- Install Vite for client folder (npm create vite@latest)
On the server folder , create some file index.js, db.js, and routes.js.

**Comment by jdungao15** [comment]
Requirement's dependencies on backend are done. Order and Cart Endpoints API needs to be work on.
